# where the helper scrip convmatrix is
SCRIPTDIR=../../../../bin
# where is the matrix generated by gencoords
DATADIR=../tmp

echo $SCRIPTDIR/convmatrix 771 bin $DATADIR/G_M.imatrix.bin inv bin $DATADIR/G_invM.imatrix.bin
$SCRIPTDIR/convmatrix 771 bin $DATADIR/G_M.imatrix.bin inv bin $DATADIR/G_invM.imatrix.bin

